final class TestingData {

  //   paste this data into the
//    request body at  localhost:8080/students/add/list/ (in Postman for example)

//           [
//    {"firstName": "John", "lastName": "Doe", "email": "john.doe@example1.com"},
//    {"firstName": "Alice", "lastName": "Smith", "email": "alice.smith@example2.com"},
//    {"firstName": "Bob", "lastName": "Johnson", "email": "bob.johnson@example3.com"},
//    {"firstName": "Emily", "lastName": "Williams", "email": "emily.williams@example4.com"},
//    {"firstName": "Michael", "lastName": "Jones", "email": "michael.jones@example5.com"},
//    {"firstName": "Olivia", "lastName": "Brown", "email": "olivia.brown@example6.com"},
//    {"firstName": "Daniel", "lastName": "Davis", "email": "daniel.davis@example7.com"},
//    {"firstName": "Sophia", "lastName": "Miller", "email": "sophia.miller@example8.com"},
//    {"firstName": "Matthew", "lastName": "Wilson", "email": "matthew.wilson@example9.com"},
//    {"firstName": "Emma", "lastName": "Moore", "email": "emma.moore@example10.com"},
//    {"firstName": "Ethan", "lastName": "Taylor", "email": "ethan.taylor@example11.com"},
//    {"firstName": "Ava", "lastName": "Anderson", "email": "ava.anderson@example12.com"},
//    {"firstName": "William", "lastName": "Thomas", "email": "william.thomas@example13.com"},
//    {"firstName": "Mia", "lastName": "White", "email": "mia.white@example14.com"},
//    {"firstName": "Liam", "lastName": "Harris", "email": "liam.harris@example15.com"},
//    {"firstName": "Charlotte", "lastName": "Martin", "email": "charlotte.martin@example16.com"},
//    {"firstName": "James", "lastName": "Jackson", "email": "james.jackson@example17.com"},
//    {"firstName": "Amelia", "lastName": "Lee", "email": "amelia.lee@example18.com"},
//    {"firstName": "Benjamin", "lastName": "Allen", "email": "benjamin.allen@example19.com"},
//    {"firstName": "Ella", "lastName": "Young", "email": "ella.young@example20.com"},
//    {"firstName": "Lucas", "lastName": "Scott", "email": "lucas.scott@example21.com"},
//    {"firstName": "Lily", "lastName": "King", "email": "lily.king@example22.com"},
//    {"firstName": "Alexander", "lastName": "Wright", "email": "alexander.wright@example23.com"},
//    {"firstName": "Grace", "lastName": "Evans", "email": "grace.evans@example24.com"},
//    {"firstName": "Henry", "lastName": "Baker", "email": "henry.baker@example25.com"},
//    {"firstName": "Chloe", "lastName": "Green", "email": "chloe.green@example26.com"},
//    {"firstName": "Sebastian", "lastName": "Turner", "email": "sebastian.turner@example27.com"},
//    {"firstName": "Sofia", "lastName": "Cooper", "email": "sofia.cooper@example28.com"},
//    {"firstName": "Jackson", "lastName": "Hill", "email": "jackson.hill@example29.com"},
//    {"firstName": "Madison", "lastName": "Nelson", "email": "madison.nelson@example30.com"},
//    {"firstName": "Aiden", "lastName": "Carter", "email": "aiden.carter@example31.com"},
//    {"firstName": "Scarlett", "lastName": "Ward", "email": "scarlett.ward@example32.com"},
//    {"firstName": "Logan", "lastName": "Fisher", "email": "logan.fisher@example33.com"},
//    {"firstName": "Abigail", "lastName": "Collins", "email": "abigail.collins@example34.com"},
//    {"firstName": "Gabriel", "lastName": "Kelly", "email": "gabriel.kelly@example35.com"},
//    {"firstName": "Zoe", "lastName": "Rogers", "email": "zoe.rogers@example36.com"},
//    {"firstName": "Wyatt", "lastName": "Perry", "email": "wyatt.perry@example37.com"},
//    {"firstName": "Natalie", "lastName": "Long", "email": "natalie.long@example38.com"},
//    {"firstName": "Caleb", "lastName": "Reed", "email": "caleb.reed@example39.com"},
//    {"firstName": "Violet", "lastName": "Cole", "email": "violet.cole@example40.com"},
//    {"firstName": "Ryan", "lastName": "Spencer", "email": "ryan.spencer@example41.com"},
//    {"firstName": "Hailey", "lastName": "Stewart", "email": "hailey.stewart@example42.com"},
//    {"firstName": "Jack", "lastName": "Harrison", "email": "jack.harrison@example43.com"},
//    {"firstName": "Layla", "lastName": "Barnes", "email": "layla.barnes@example44.com"},
//    {"firstName": "Andrew", "lastName": "Graham", "email": "andrew.graham@example45.com"},
//    {"firstName": "Paisley", "lastName": "Pierce", "email": "paisley.pierce@example46.com"},
//    {"firstName": "Nathan", "lastName": "Matthews", "email": "nathan.matthews@example47.com"},
//    {"firstName": "Ellie", "lastName": "Russell", "email": "ellie.russell@example48.com"},
//    {"firstName": "Owen", "lastName": "Dixon", "email": "owen.dixon@example49.com"},
//    {"firstName": "Aria", "lastName": "Gordon", "email": "aria.gordon@example50.com"}
//  ]
//
}
